'use strict';
// ⚠️ Part of this file is automatically generated
//    The :RUNTIMES comment is a delimiter and no code should be written/changed after
//    See rollup/build_interpreters.cjs to know more

const { base } = require("./interpreter/_utils.js");

/** @type {Map<string, object>} */
const registry = new Map();
exports.registry = registry;

/** @type {Map<string, object>} */
const configs = new Map();
exports.configs = configs;

/** @type {string[]} */
const selectors = [];
exports.selectors = selectors;

/** @type {string[]} */
const prefixes = [];
exports.prefixes = prefixes;

const interpreter = new Proxy(new Map(), {
    get(map, id) {
        if (!map.has(id)) {
            const [type, ...rest] = id.split("@");
            const interpreter = registry.get(type);
            const url = /^https?:\/\//i.test(rest)
                ? rest.join("@")
                : interpreter.module(...rest);
            map.set(id, {
                url,
                module: import(url),
                engine: interpreter.engine.bind(interpreter),
            });
        }
        const { url, module, engine } = map.get(id);
        return (config, baseURL) =>
            module.then((module) => {
                configs.set(id, config);
                const fetch = config?.fetch;
                if (fetch) base.set(fetch, baseURL);
                return engine(module, config, url);
            });
    },
});
exports.interpreter = interpreter;

const register = (interpreter) => {
    for (const type of [].concat(interpreter.type)) {
        registry.set(type, interpreter);
        selectors.push(`script[type="${type}"]`);
        prefixes.push(`${type}-`);
    }
};

//:RUNTIMES
const micropython = (m => /* c8 ignore start */ m.__esModule ? m.default : m /* c8 ignore stop */)(require("./interpreter/micropython.js"));
const pyodide = (m => /* c8 ignore start */ m.__esModule ? m.default : m /* c8 ignore stop */)(require("./interpreter/pyodide.js"));
const ruby_wasm_wasi = (m => /* c8 ignore start */ m.__esModule ? m.default : m /* c8 ignore stop */)(require("./interpreter/ruby-wasm-wasi.js"));
const wasmoon = (m => /* c8 ignore start */ m.__esModule ? m.default : m /* c8 ignore stop */)(require("./interpreter/wasmoon.js"));
for (const interpreter of [micropython, pyodide, ruby_wasm_wasi, wasmoon])
    register(interpreter);
